authors:
  mrxsierra:
    name: Sunil Sharma
    description: Full-Stack Architect & Machine Learning Engineer
    avatar: https://avatars.githubusercontent.com/u/9698455
    url: https://github.com/mrxsierra